---
name: Anti AFK
author: BNT Feujjj
main: BNTFeujjj\AntiAFK\Main
api:
- 5.0.0
version: 2.0.0
commands:
  afkreload:
    usage: /afkreload
    description: Reload la config de l'antiafk.
    permission: antiafk.cmd.reload
permissions:
  antiafk.cmd.reload:
    default: op
  antiafk.bypass:
    default: op
...
